spring.application.name=techmovil

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/techmovil_db
spring.datasource.username=root
spring.datasource.password=12345678

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Seguridad JWT
# Nota: En producción, usa un secreto más largo y seguro guardado en variables de entorno
app.jwt.secret=techmovil_backend_secret_key_2026_puno_peru_electronics_store
app.jwt.expiration-ms=86400000