# ============================================================
# PERFIL: Produccion (valores desde variables de entorno)
# ============================================================
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.jwt.secret=
app.jwt.expiration-ms=86400000
app.igv.porcentaje=18.00
